# render.yaml - VERSÃO 3, COM PLANO DE BD ATUALIZADO
version: "1"

databases:
  - name: fisgarone-db
    plan: "free" # Usa o plano gratuito para passar da validação inicial.
    databaseName: fisgarone_db_data
    user: fisgarone_user

services:
  - type: web
    name: fisgarone-erp
    runtime: python
    plan: starter # O plano 'starter' para web services ainda é válido.
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fisgarone-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.12"
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: "run:app"
