# render.yaml - VERSÃO CORRIGIDA E VALIDADA
version: "1"

services:
  # 1. O Serviço Web (sua aplicação Flask/Gunicorn)
  - type: web
    name: fisgarone-erp
    runtime: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars:
      - key: DATABASE_URL
        # Pega a URL de conexão do banco de dados definido abaixo
        fromService:
          type: psql # O tipo correto para PostgreSQL
          name: fisgarone-db
          property: connectionString # Esta propriedade é válida para o tipo 'psql'
      - key: PYTHON_VERSION
        value: "3.12"
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: "run:app"

  # 2. O Banco de Dados PostgreSQL Gerenciado
  - type: psql # O tipo correto para um banco de dados PostgreSQL
    name: fisgarone-db
    plan: starter # O plano 'starter' é suficiente para começar

