# render.yaml - VERSÃO 2, CORRIGIDA COM SINTAXE OFICIAL
version: "1"

databases:
  # Define o banco de dados a ser criado
  - name: fisgarone-db
    # 'postgres' é o tipo de banco de dados
    databaseName: fisgarone_db_data # Nome interno do banco de dados
    user: fisgarone_user
    plan: starter

services:
  # Define o serviço web
  - type: web
    name: fisgarone-erp
    runtime: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars:
      - key: DATABASE_URL
        # Obtém a URL de conexão do banco de dados definido acima
        fromDatabase:
          name: fisgarone-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.12"
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: "run:app"
