"""Adiciona colunas custo_operacional_ml e mc_ml a VendaML

Revision ID: 0a91624f77d2
Revises: 80e40277f82f
Create Date: 2025-11-02 13:49:55.253624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a91624f77d2'
down_revision = '80e40277f82f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integration_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ml_seller_id', sa.String(length=50), nullable=True))

    with op.batch_alter_table('vendas_ml', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custo_operacional_ml', sa.Numeric(precision=10, scale=2), nullable=True, comment='Custo total da venda no canal ML (Comissão + Taxa Fixa + Frete)'))
        batch_op.add_column(sa.Column('mc_ml', sa.Numeric(precision=10, scale=2), nullable=True, comment='Margem de Contribuição da venda (Receita - Custo Canal - Custo Produto)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas_ml', schema=None) as batch_op:
        batch_op.drop_column('mc_ml')
        batch_op.drop_column('custo_operacional_ml')

    with op.batch_alter_table('integration_configs', schema=None) as batch_op:
        batch_op.drop_column('ml_seller_id')

    # ### end Alembic commands ###
