"""Add ml_seller_id to IntegrationConfig

Revision ID: 80e40277f82f
Revises: fc03fe803072
Create Date: 2025-10-31 10:47:24.830488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e40277f82f'
down_revision = 'fc03fe803072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integration_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ml_seller_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integration_configs', schema=None) as batch_op:
        batch_op.drop_column('ml_seller_id')

    # ### end Alembic commands ###
