"""Create companies tables and update users

Revision ID: bea934aa6fc3
Revises: 
Create Date: 2025-10-27 16:01:10.839324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea934aa6fc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('cnpj', sa.String(length=18), nullable=False),
        sa.Column('razao_social', sa.String(length=200), nullable=False),
        sa.Column('nome_fantasia', sa.String(length=200), nullable=True),
        sa.Column('email', sa.String(length=120), nullable=True),
        sa.Column('telefone', sa.String(length=20), nullable=True),
        sa.Column('cep', sa.String(length=10), nullable=True),
        sa.Column('logradouro', sa.String(length=200), nullable=True),
        sa.Column('numero', sa.String(length=20), nullable=True),
        sa.Column('complemento', sa.String(length=100), nullable=True),
        sa.Column('bairro', sa.String(length=100), nullable=True),
        sa.Column('cidade', sa.String(length=100), nullable=True),
        sa.Column('estado', sa.String(length=2), nullable=True),
        sa.Column('ativo', sa.Boolean(), nullable=True),
        sa.Column('data_criacao', sa.DateTime(), nullable=True),
        sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('cnpj'),
        mysql_row_format='DYNAMIC'
    )
    op.create_table('company_configs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('timezone', sa.String(length=50), nullable=True),
        sa.Column('idioma', sa.String(length=10), nullable=True),
        sa.Column('moeda', sa.String(length=10), nullable=True),
        sa.Column('auto_sincronizar_estoque', sa.Boolean(), nullable=True),
        sa.Column('auto_processar_pedidos', sa.Boolean(), nullable=True),
        sa.Column('intervalo_sincronizacao', sa.Integer(), nullable=True),
        sa.Column('data_criacao', sa.DateTime(), nullable=True),
        sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
        sa.PrimaryKeyConstraint('id'),
        mysql_row_format='DYNAMIC'
    )
    op.create_table('integration_configs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('ml_ativo', sa.Boolean(), nullable=True),
        sa.Column('ml_app_id', sa.String(length=100), nullable=True),
        sa.Column('ml_client_secret', sa.String(length=100), nullable=True),
        sa.Column('ml_access_token', sa.Text(), nullable=True),
        sa.Column('ml_refresh_token', sa.Text(), nullable=True),
        sa.Column('ml_token_expires', sa.DateTime(), nullable=True),
        sa.Column('shopee_ativo', sa.Boolean(), nullable=True),
        sa.Column('shopee_partner_id', sa.String(length=100), nullable=True),
        sa.Column('shopee_secret_key', sa.String(length=100), nullable=True),
        sa.Column('shopee_access_token', sa.Text(), nullable=True),
        sa.Column('shopee_refresh_token', sa.Text(), nullable=True),
        sa.Column('sincronizar_pedidos_auto', sa.Boolean(), nullable=True),
        sa.Column('sincronizar_produtos_auto', sa.Boolean(), nullable=True),
        sa.Column('sincronizar_estoque_auto', sa.Boolean(), nullable=True),
        sa.Column('data_criacao', sa.DateTime(), nullable=True),
        sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
        sa.PrimaryKeyConstraint('id'),
        mysql_row_format='DYNAMIC'
    )
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('integration_configs')
    op.drop_table('company_configs')
    op.drop_table('companies')
    # ### end Alembic commands ###
