"""Add ativo column to companies

Revision ID: fc03fe803072
Revises: bea934aa6fc3
Create Date: 2025-10-30 19:35:52.049374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc03fe803072'
down_revision = 'bea934aa6fc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custos_ml',
    sa.Column('mlb', sa.String(length=100), nullable=False),
    sa.Column('custo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('mlb')
    )
    op.create_table('repasses_ml',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.String(length=100), nullable=True),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_venda', sa.String(length=20), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('tipo_logistica', sa.String(length=50), nullable=True),
    sa.Column('situacao', sa.String(length=50), nullable=True),
    sa.Column('taxa_fixa_ml', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comissoes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('frete_seller', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_liberacao', sa.String(length=20), nullable=True),
    sa.Column('data_repasse', sa.String(length=20), nullable=True),
    sa.Column('total_venda', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_custo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_repasse', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('conta', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendas_ml',
    sa.Column('id_pedido', sa.String(length=100), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('data_venda', sa.String(length=20), nullable=True),
    sa.Column('taxa_mercado_livre', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('taxa_fixa_ml', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comissoes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comissao_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('frete', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('custo_frete_base', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('custo_frete_opcional', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('custo_pedido_frete', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('custo_lista_frete', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('custo_total_frete', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('frete_comprador', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('frete_seller', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('titulo', sa.String(length=500), nullable=True),
    sa.Column('mlb', sa.String(length=100), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('codigo_envio', sa.String(length=100), nullable=True),
    sa.Column('comprador', sa.String(length=100), nullable=True),
    sa.Column('modo_envio', sa.String(length=100), nullable=True),
    sa.Column('tipo_logistica', sa.String(length=50), nullable=True),
    sa.Column('pago_por', sa.String(length=20), nullable=True),
    sa.Column('situacao', sa.String(length=50), nullable=True),
    sa.Column('situacao_entrega', sa.String(length=50), nullable=True),
    sa.Column('cancelamentos', sa.String(length=20), nullable=True),
    sa.Column('data_liberacao', sa.String(length=20), nullable=True),
    sa.Column('preco_custo_ml', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('custo_total_calculado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('aliquota_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('imposto_rs', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('custo_operacional', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_custo_operacional', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mc_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('custo_fixo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lucro_real', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lucro_real_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('conta', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('nome_fantasia',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('cep')
        batch_op.drop_column('numero')
        batch_op.drop_column('email')
        batch_op.drop_column('bairro')
        batch_op.drop_column('estado')
        batch_op.drop_column('cidade')
        batch_op.drop_column('logradouro')
        batch_op.drop_column('data_criacao')
        batch_op.drop_column('telefone')
        batch_op.drop_column('data_atualizacao')
        batch_op.drop_column('complemento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complemento', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('data_atualizacao', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('telefone', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('data_criacao', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('logradouro', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('cidade', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=2), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('numero', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.VARCHAR(length=10), nullable=True))
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('nome_fantasia',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    op.drop_table('vendas_ml')
    op.drop_table('repasses_ml')
    op.drop_table('custos_ml')
    # ### end Alembic commands ###
